baseURL = "https://schulichignite.com/"
languageCode = "en-us"
title = "Schulich Ignite"
summaryLength = 20
relativeURLs = true

[params]
    email = "info@schulichignite.com"
    signup = false
    mentorSignUp = "http://docs.google.com/forms/d/e/1FAIpQLScfUYoFgFsdN5uJShpq0CjxmuU9MEdXpjf2w9QXxxc9sdYztQ/viewform?usp=sf_link"
    menteeSignUp = "https://docs.google.com/forms/d/e/1FAIpQLSe4fThK2EJ76m5MPLg99AMpNCjl6y5xPYeYbzXxwEu-RKA5Vg/viewform"
    ignitePoints = "https://docs.google.com/spreadsheets/d/1iyzEQ-rgPnUfVVIvJK2HBrGn6l6HatGrT6i3GLoxdUM/edit?usp=sharing"
    sparkDocs    = "https://schulichignite.com/spark/"
    submitBugBusters   = "https://docs.google.com/forms/d/e/1FAIpQLSdZR34VwCzT0OXWggC9OoGtjNd_EJH-qqa2oguWvy6oL2w0BQ/viewform"
    submitPythonicLava = "https://docs.google.com/forms/d/e/1FAIpQLSeQJ2hzXyIgfWkYnCNeHfg9uvvsJyZCT5Wv3qFTq5EuoJgS9w/viewform"
    startDate = 2020-10-17
    endDate   = 2020-12-08
    [params.links]
        youtube = "https://www.youtube.com/channel/UC7tNvdbu952HOUl_4nK7iww"
        instagram = "https://www.instagram.com/schulichignite"
        facebook = "https://www.facebook.com/SchulichIgnite/"
        linkedin = "https://linkedin.com/company/schulich-ignite/"
        discord = "https://discord.gg/F3Qjqqj"
        tiktok  = "https://vm.tiktok.com/ZSHPbWU3/"
