baseURL = "https://dev.schulichignite.com/" # TODO: Change to schulichignite.com on launch
languageCode = "en-us"
title = "Schulich Ignite"
summaryLength = 20
relativeURLs = true

[params]
    email = "info@schulichignite.com"
    signup = true
    mentorSignUp = "http://docs.google.com/forms/d/e/1FAIpQLScfUYoFgFsdN5uJShpq0CjxmuU9MEdXpjf2w9QXxxc9sdYztQ/viewform?usp=sf_link"
    menteeSignUp = "https://docs.google.com/forms/d/1C-Mc5IerY6yDLNI-2hRyZtmMZtSSPdTyJfWPnDpBO-0/"
    [params.links]
        youtube = "https://www.youtube.com/channel/UC7tNvdbu952HOUl_4nK7iww"
        instagram = "https://www.instagram.com/schulichignite"
        facebook = "https://www.facebook.com/SchulichIgnite/"
        linkedin = "https://linkedin.com/company/schulich-ignite/"
        discord = "https://discord.gg/F3Qjqqj"
