baseURL = "https://schulichignite.com/"
languageCode = "en-us"
title = "Schulich Ignite"
summaryLength = 20

[params]
    email = "info@schulichignite.com"
    signup = true
    [params.links]
        youtube = "https://www.youtube.com/channel/UC7tNvdbu952HOUl_4nK7iww"
        instagram = "https://www.instagram.com/schulichignite"
        facebook = "https://www.facebook.com/SchulichIgnite/"
        linkedin = "https://linkedin.com/company/schulich-ignite/"
        discord = "https://discord.gg/F3Qjqqj"