name: Publish Site

on:
  push:
    branches:
      - gh-pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Auto Minify
        uses: nizarmah/auto-minify@master

      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action
        with:
          commit_message: "Github Action: Auto Minified JS and CSS files"
          branch: ${{ github.ref }}
